apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: xyv3gbqsi-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: xyv3gbqsi-go 
  name: xyv3gbqsi-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: xyv3gbqsi-go 
